events {
    worker_connections 1024;
}

http {
    upstream app {
        server app-python:5000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass         http://app;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /health {
            return 200 "nginx OK\n";
            add_header Content-Type text/plain;
        }
    }
}